# ── Stage 1: pinned base image ───────────────────────────────────────────────
FROM node:24-alpine AS base

# ── Stage 2: install deps + build ────────────────────────────────────────────
FROM base AS builder

# Required by some native add-ons on Alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

# ── Build-time arguments ──────────────────────────────────────────────────────
# All are optional at build time; Next.js only needs them baked in if you use
# server-side static generation that calls the DB/auth at build time.
# At runtime they are supplied via docker run --env-file or docker-compose.
ARG NODE_ENV=production
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL=http://localhost:3000
ARG MONGODB_URI
ARG MSSQL_HOST
ARG MSSQL_PORT=1433
ARG MSSQL_DB
ARG MSSQL_USER
ARG MSSQL_PASSWORD

# Expose as environment variables for the build step
ENV NODE_ENV=$NODE_ENV \
    NEXTAUTH_SECRET=$NEXTAUTH_SECRET \
    NEXTAUTH_URL=$NEXTAUTH_URL \
    MONGODB_URI=$MONGODB_URI \
    MSSQL_HOST=$MSSQL_HOST \
    MSSQL_PORT=$MSSQL_PORT \
    MSSQL_DB=$MSSQL_DB \
    MSSQL_USER=$MSSQL_USER \
    MSSQL_PASSWORD=$MSSQL_PASSWORD \
    NEXT_TELEMETRY_DISABLED=1

# Debug — confirm args arrived (password masked)
RUN echo "=== Build-time environment ===" && \
    echo "NODE_ENV:      $NODE_ENV"       && \
    echo "NEXTAUTH_URL:  $NEXTAUTH_URL"   && \
    echo "MONGODB_URI:   $MONGODB_URI"    && \
    echo "MSSQL_HOST:    $MSSQL_HOST"     && \
    echo "MSSQL_PORT:    $MSSQL_PORT"     && \
    echo "MSSQL_DB:      $MSSQL_DB"       && \
    echo "MSSQL_USER:    $MSSQL_USER"     && \
    echo "MSSQL_PASSWORD: [hidden]"

# Install ALL dependencies (including devDeps) — needed for tailwindcss/postcss at build time
COPY package.json package-lock.json* ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci --include=dev --prefer-offline

# Copy source after deps so code changes don't bust the dep cache layer
COPY . .

# Build the Next.js standalone bundle
RUN npm run build

# Debug — confirm standalone output was produced
RUN echo "=== .next/standalone contents ===" && ls -la .next/standalone

# ── Stage 3: minimal production runner ───────────────────────────────────────
FROM base AS runner

WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000

# Create a non-root user with a real home directory
RUN mkdir -p /home/appuser && \
    addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 --home /home/appuser appuser && \
    chown -R appuser:nodejs /app /home/appuser

# Pre-create the .next dir with correct ownership before the COPY
RUN mkdir .next && chown appuser:nodejs .next

# Copy only what Next.js standalone needs — no node_modules, no source
COPY --from=builder --chown=appuser:nodejs /app/.next/standalone ./
COPY --from=builder --chown=appuser:nodejs /app/.next/static     ./.next/static
COPY --from=builder --chown=appuser:nodejs /app/public           ./public

# Debug — confirm the runner has everything it needs
RUN echo "=== /app contents ===" && ls -la && \
    echo "=== .next contents ===" && ls -la .next

# curl + wget for health checks / liveness probes


# Drop to non-root
USER appuser
ENV HOME=/home/appuser

EXPOSE 3000

# server.js is generated by Next.js standalone output — lighter than `next start`
CMD HOSTNAME="0.0.0.0" node server.js

