// Run: node scripts/seed-clients.js
require("dotenv").config({ path: ".env.local" });
const mongoose = require("mongoose");

const CLIENTS = [
  { code: "I2254", name: "ADITYA BIRLA PENSION -E - TIER I" },
  { code: "I4050", name: "ANTARA INDIA EVERGREEN FUND (FPI)" },
  { code: "I4113", name: "Asit C. Mehta - ACE ALLOCATOR" },
  { code: "I2146", name: "AXIS PENSION FUND - E TIER I" },
  { code: "I1146", name: "BARODA BNP PARIBAS MULTI CAP FUND" },
  { code: "I2086", name: "DSP PENSION SCHEME G TIER-II" },
  { code: "I2121", name: "EDELWEISS LIFE INSURANCE COMPANY LIMITED- ELI" },
  { code: "I1313", name: "Edelweiss ELSS TAX Saver Fund" },
  { code: "I4061", name: "DYNAMIC EQUITIES PVT.LTD" },
  { code: "I1949", name: "GROWW MF - LARGE CAP FUND" },
  { code: "I1322", name: "IDBI BANK LTD SCHEME - 1" },
  { code: "I2191", name: "ITI MF MULTI CAP FUND" },
  { code: "I4107", name: "INDIA EMERGING GIANTS FUND LIMITED" },
  { code: "I4042", name: "ITI LONG SHORT EQUITY FUND" },
  { code: "I2005", name: "JM MF JM VALUE FUND" },
  { code: "I4084", name: "KITARA GROWTH FUND -2024" },
  { code: "I1081", name: "LIC MF Unit Linked Insurance Scheme (ULIS)" },
  { code: "I5000", name: "LIFE INSURANCE Scheme - 05" },
  { code: "I1543", name: "LIC PENSION FUND CENTRAL GOVT SCHEME -1" },
  { code: "I1751", name: "MAHINDRA MANULIFE ELSS TAX SAVER FUND" },
  { code: "I4103", name: "MOTILAL OSWAL WEALTH LIMITED - DELPHI ALPHA EDGE PMS" },
  { code: "I1965", name: "NAVI GENERAL INSU POLICYHOLDER FUND" },
  { code: "I1336", name: "NAVI MF REGULAR SAVING FUND" },
  { code: "I1961", name: "NJ BALANCED ADVANTAGE FUND" },
  { code: "I4057", name: "NUVAMA ENHANCED DYNAMIC GROWTH EQUITY(EDGE)FUND" },
  { code: "I4063", name: "NUVAMA ASSET MANAGEMENT LIMITED - NEXT" },
  { code: "I1878", name: "PGIM INDIA LARGE CAP FUND" },
  { code: "TAXSAVER", name: "PARAG PARIKH TAX SAVER FUND" },
  { code: "I4010", name: "PROFUSION INVESTMENT ADVISORS LLP" },
  { code: "I1029", name: "QUANT MF SMALL CAP FUND" },
  { code: "I4012", name: "AYAZ ZAKARIA MEMON" },
  { code: "I4013", name: "SUBRAMANIAN MAYOORANATHAN IYER" },
  { code: "I1130", name: "Quantum Value Fund" },
  { code: "I4127", name: "QUEST INVESTMENT - QUEST PMS MULTI - STRATEGY" },
  { code: "I1972", name: "SAMCO FLEXI CAP FUND" },
  { code: "I4003", name: "SANCTUM WEALTH - SMART SOLUTION" },
  { code: "I1566", name: "SBI GENERAL INSU SCHEME - ESMA" },
  { code: "I1028", name: "SBI LIFE INSURANCE CO. LTD" },
  { code: "I2033", name: "SHRIRAM GENERAL INSURANCE COMPANY LIMITED" },
  { code: "I1275", name: "SHRIRAM LIFE INSURANCE COMPANY LIMITED" },
  { code: "I1793", name: "SHRIRAM AGGRESSIVE HYBRID FUND" },
  { code: "I1195", name: "SUNDARAM CONSUMPTION FUND ( RURAL)" },
  { code: "I1119", name: "TAURUS MF FLEXI FUND" },
  { code: "I4081", name: "TCG ADVISORY SERVICES PVT LTD -TCG LIQUID PORTFOLIO" },
  { code: "I4036", name: "VARANIUM INDIA OPPORTUNITY LTD" },
  { code: "I1811", name: "ZUNO GI INVESTMENT ASSETS" },
  { code: "I4121", name: "31 DEGREES NORTH FUND-31 DEGREES NORTH FUND I" },
  { code: "I1646", name: "AGRICULTURE INSURANCE COMPANY OF INDIA LTD" },
  { code: "I4120", name: "AIF-Laureate" },
  { code: "I4078", name: "AMICORP CAPITAL (MAURITIUS) LIMITED" },
  { code: "I4106", name: "AMRIT KAAL OPPORTUNITIES FUND" },
  { code: "I4092", name: "ANGEL ONE INVESTMENT MANAGERS&ADVISORS PVT LTD" },
  { code: "I4016", name: "AVIATOR GLOBAL INVESTMENT FUND" },
  { code: "I2079", name: "AVIVA LIFE INSURANCE COMPANY INDIA LIMITE" },
  { code: "I1003", name: "AXIS BANK LTD." },
  { code: "I4046", name: "AYUSHI DMCC" },
  { code: "I1937", name: "BANDHAN BANK LIMITED" },
  { code: "I1148", name: "BANK OF BARODA" },
  { code: "I1002", name: "BANK OF INDIA" },
  { code: "I1024", name: "BANK OF MAHARASTHRA" },
  { code: "I4080", name: "BFLY INDIA OPPORTUNITIES FUND" },
  { code: "I1962", name: "BGR ODISHA POWERGEN LIMITED" },
  { code: "I4062", name: "BLUE LOTUS CAPITAL MULTI BAGGER FUND II" },
  { code: "CANBK",  name: "CANARA BANK" },
  { code: "I4014", name: "CAPGROW CAPITAL ADVISOR LLP" },
  { code: "I1080", name: "CENTRAL BANK OF INDIA" },
  { code: "I1103", name: "CITI UNION BANK" },
  { code: "I4001", name: "COMPOUND EVERYDAY CAPITAL MANAGEMENT LLP PMS" },
  { code: "I2047", name: "CREDITACCESS LIFE INSURANCE LIMITED" },
  { code: "I1312", name: "CSB BANK LTD" },
  { code: "I4086", name: "DALMUS PERFORMANCE FOCUSED FUND" },
  { code: "I1344", name: "DCB BANK LIMITED" },
  { code: "I1997", name: "DHANLAXMI BANK LIMITED" },
  { code: "I1781", name: "DOHA BANK QSC INDIA BRANCHES" },
  { code: "I4033", name: "DOVETAIL GLOBAL FUND PCC - CELL 17" },
  { code: "I1852", name: "ECGC LTD" },
  { code: "I4091", name: "EMERGE CAPITAL OPPORTUNITIES SCHEME" },
  { code: "I2133", name: "ESAF SMALL FINANCE BANK LIMITED" },
  { code: "I1075", name: "EXPORT IMPORT BANK OF INDIA" },
  { code: "I4039", name: "FIRST WATER CAPITAL FUND - II" },
  { code: "I4098", name: "FORT CAPITAL INVESTMENT ADVISORY PRIVATE LIMITED Value" },
  { code: "I1288", name: "GENERAL INSURANCE CORPORATION" },
  { code: "I2131", name: "GO Digit General Insurance Limited" },
  { code: "I2165", name: "GO DIGIT LIFE INSURANCE LIMITED" },
  { code: "I1317", name: "HDFC BANK LIMITED" },
  { code: "I1690", name: "ICICI BANK LTD TRADING A/C" },
  { code: "I2036", name: "IFFCO TOKIO GENERAL INSURANCE CO LTD" },
  { code: "I4104", name: "India Insight Value Fund" },
  { code: "I1318", name: "INDIAFIRST LIFE INSURANCE COMPANY LIMITED" },
  { code: "I1025", name: "INDIAN BANK" },
  { code: "I1010", name: "INDIAN OVERSEAS BANK" },
  { code: "I2128", name: "INDUSIND BANK LTD" },
  { code: "I4018", name: "I-WEALTH FUND 2" },
  { code: "I4056", name: "JM FINANCIAL LIMITED APEX PORTFOLIO" },
  { code: "I1127", name: "KARNATAKA BANK" },
  { code: "I1823", name: "KARUR VYSYA BANK LTD" },
  { code: "I4105", name: "KNIGHTSTONE CAPITAL LLP" },
  { code: "I2136", name: "KSHEMA GENERAL INSURANCE LIMITED" },
  { code: "I4055", name: "KUO PO CHIANG" },
  { code: "I1187", name: "LAKSHMI VILAS BANK LIMITED" },
  { code: "I4060", name: "M7 GLOBAL FUND PCC- CELL DEWCAP FUND" },
  { code: "I1866", name: "MAHARSHTRA GRAMIN BANK" },
  { code: "I1339", name: "MARSHAL INDIA SELECT FUND LTD" },
  { code: "I4095", name: "Matterhorn India Fund" },
  { code: "I4128", name: "MBS INDIA INVESTMENTS LLC" },
  { code: "I4066", name: "METEOR CAPITAL FUND VCC-METEOR GLOBAL PORTFOLIO INCORPORATED VCC SUB-F" },
  { code: "I4125", name: "MONEYBEE INVESTMENT TRUST - FLYINGBEE INVESTMENT FUND" },
  { code: "I4144", name: "MONEYGROW ASSET PRIVATE LIMITED" },
  { code: "I4096", name: "MONIKA GARWARE" },
  { code: "I2044", name: "NATIONAL BANK FOR AGRICULTURE AND RURAL DEVE" },
  { code: "I4068", name: "NEW APPOLO DMCC" },
  { code: "I4015", name: "NEW LEAINA INVESTMENTS LIMITED" },
  { code: "I4093", name: "NEXUS EQUITY GROWTH FUND - NEXUS EQUITY GROWTH FUND SCH-1" },
  { code: "I2166", name: "NIVA BUPA HEALTH INSURANCE COMPANY LIMITED" },
  { code: "I4070", name: "NV ALPHA FUND MANAGEMENT LLP" },
  { code: "I4027", name: "OAKLANE CAPITAL MANAGEMENT LLP" },
  { code: "I4034", name: "OCULUS CAPITAL ALTERNATIVE INVESTMENT FUND-OCULUS CAPITAL GROWTH FUND" },
  { code: "I1035", name: "ORIENTAL INSURANCE CO. LIMITED" },
  { code: "I4032", name: "PLURIS FUND LIMITED" },
  { code: "I1519", name: "PLUTUS TERRA INDIA FUND" },
  { code: "I1569", name: "PNB GILTS LTD" },
  { code: "I2098", name: "PNB METLIFE INDIA INSURANCE COMPANY LIMITED" },
  { code: "I4054", name: "PROFITGATE CAPITAL SERVICES LLP" },
  { code: "I4037", name: "PRP EDGE WEALTH PRIVATE LIMITED" },
  { code: "I1005", name: "PUNJAB AND SIND BANK" },
  { code: "PNBK",   name: "PUNJAB NATIONAL BANK" },
  { code: "I1350", name: "RBL BANK LIMITED" },
  { code: "I4044", name: "RBSA INVESTMENT MANAGER LLP" },
  { code: "I2037", name: "RESONANCE OPPORTUNITIES FUND" },
  { code: "I4090", name: "ROHA VENTURE FIRM" },
  { code: "I1283", name: "SBI DFHI LTD" },
  { code: "I1138", name: "SIDBI" },
  { code: "I1287", name: "STAR UNION DAI-ICHI LIFE INSURANCE" },
  { code: "STC",    name: "STCI FINANCE LIMITED" },
  { code: "I1651", name: "STCIPD LTD" },
  { code: "I4076", name: "SWYOM ADVISORS LIMITED - SWYOM INDIA OPPORTUNITIES FUND" },
  { code: "I4100", name: "SWYOM INDIA ALPHA FUND" },
  { code: "I1036", name: "TAMILNAD MERCANTILE BANK LTD" },
  { code: "I4101", name: "The Asio Fund VCC - Hathi Capital India Growth Fund I" },
  { code: "I1079", name: "THE FEDERAL BANK" },
  { code: "I4019", name: "THE GREAT INTERNATIONAL TUSKER FUND" },
  { code: "I1104", name: "THE SOUTH INDIAN BANK" },
  { code: "I1012", name: "UCO BANK" },
  { code: "I2096", name: "UJJIVAN SMALL FINANCE BANK LIMITED" },
  { code: "I2169", name: "UNIFI MUTUAL FUND - UNIFI FLEXI CAP FUND" },
  { code: "I1001", name: "UNION BANK OF INDIA (NEW)" },
  { code: "I1136", name: "UNITED INDIA INSURANCE CO. LTD," },
  { code: "I1356", name: "UNIVERSAL SOMPO GENERAL INSU. LTD" },
  { code: "I4124", name: "VALUE WISE UNDISCOVERED FUND" },
  { code: "I2176", name: "VALUEATTICS REINSURANCE LIMITED" },
  { code: "I4148", name: "VENTUREX FUND I" },
  { code: "I4143", name: "WHITE STONE FINANCIAL ADVISORS PVT LTD" },
  { code: "I4102", name: "WILDFLOWER PRIVATE TRUST" },
  { code: "I2284", name: "ABAKKUS FLEXI CAP FUND" },
  { code: "I1563", name: "LIC NOMURA MUTUAL FUND ASSET MANAGMENT CO. PVT PMS" },
  { code: "I1898", name: "Nippon Life India Asset Management Ltd." },
  { code: "I2270", name: "JANA SMALL FINANCE BANK LIMITED" },
  { code: "I1008", name: "STATE BANK OF INDIA" },
  { code: "I2286", name: "SBM BANK (INDIA) LIMITED" },
  { code: "I1004", name: "IFCI LTD" },
  { code: "I1598", name: "AUCTOR INVESTMENT LTD" },
  { code: "I4169", name: "Momentum Capital Fund" },
  { code: "I4157", name: "FINDOC INVESTMART PRIVATE LIMITED" },
  { code: "I4167", name: "FORTUNA ASSET MANAGERS LLP-DPMS" },
  { code: "I4170", name: "FYERS ASSET MANAGEMENT PRIVATE LIMITED" },
  { code: "I4160", name: "GREEN PORTFOLIO PRIVATE LIMITED" },
  { code: "I4159", name: "JADE WEALTH MANAGEMENT LLP" },
  { code: "I4164", name: "NJ ASSET MANAGEMENT PRIVATE LIMITED" },
  { code: "I4153", name: "Arihant Bharat Advantage Fund" },
  { code: "I4149", name: "Electrum AIF-Viksit Bharat Fund" },
  { code: "I4156", name: "MONOMER CAPITAL SCHEME 1" },
  { code: "I4166", name: "OHANA INDIA GROWTH FUND" },
  { code: "I4150", name: "SBI FUNDS MANAGEMENT LIMITED" },
  { code: "I1542", name: "IDFC LIMITED" },
];

async function main() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log("Connected to MongoDB:", process.env.MONGODB_URI);

  const col = mongoose.connection.collection("companies");

  let inserted = 0, skipped = 0;
  for (const client of CLIENTS) {
    const exists = await col.findOne({ code: client.code });
    if (exists) { skipped++; continue; }
    await col.insertOne({ code: client.code, name: client.name, createdAt: new Date() });
    inserted++;
  }

  console.log(`Done. Inserted: ${inserted}, Skipped (already exist): ${skipped}`);
  await mongoose.disconnect();
}

main().catch((e) => { console.error(e); process.exit(1); });
